FROM node:20-alpine

WORKDIR /app

COPY ../repository-Pygmalion-/mvp/app/package*.json ./

RUN npm install

COPY ../repository-Pygmalion-/mvp/app/ ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
